[project]
name = "server-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.2.1",
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "hypothesis>=6.148.1",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
]

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]
